### ISSUE TITLE
Cooldown monitor not showing cooldowns ; Attendance Window out of border

### ISSUE THREAD

**Issue by Zidras** [ajseward/RaidAssist_WotLK#1]
Started testing the port today and noticed the cooldown monitor not showing any registered cooldowns on the panel. Tested with Aura Mastery and HoP on self (none showed on the panel)

Also attendance window is showing elements out of window panel:
![image](https://user-images.githubusercontent.com/10605951/85018303-df55a780-b164-11ea-86bf-d0c9a3311b90.png)

**Comment by andrew6180** [comment]
Panel won't show unless you're in a party / raid group I think(?) Cooldowns are super buggy but I've never had issues of them not showing. 
I'll move the attendance stuff, just something I added quickly myself. 

![image](https://user-images.githubusercontent.com/16847730/85046871-def9e400-b145-11ea-94ca-b96246fa4f95.png)
these are my settings ~~(the checkboxes for each CD on the right don't do anything yet)~~ https://github.com/ajseward/RaidAssist_WotLK/commit/cfc64925a9ff9ee52ab42ccbacb33c5938009df5 fixed here

**Comment by Zidras** [comment]
Regarding the show panel in group conditionals, I've removed them prior to testing, trying with and without in combat on a dummy to check if Aura mastery would show, to no avail.
I'll recheck the new commits asap thanks

**Comment by Zidras** [comment]
I think I now understand how the logic works behind the show conditionals. I was considering them if not selected as a ` if not then show` but it's the opposite as they only activate if that particular conditional is selected.

1. If nothing is selected:
![image](https://user-images.githubusercontent.com/10605951/85143371-90317480-b241-11ea-9b6f-db25f0fe73d7.png)
then: it'll never show. If I'm solo so `not in party` and `not in raid`.
1.1. While solo, `In combat` and `Inside Instance` are not returning anything to show frame.

2. If I'm in group, then the logic described initially applies.
![image](https://user-images.githubusercontent.com/10605951/85144905-b7894100-b243-11ea-87df-8034496431e5.png)
2.1. Inside instances is not hiding frame when I enter Violet Hold.
2.2. In Combat disabled correctly hides when I enter combat

Also, sidenote, I don't see In Boss Encounter on my addon. Is that a dev version of yours?

**Comment by andrew6180** [comment]
I just removed boss encounters since it doesn't work anyways, it relies on api after wotlk

**Comment by andrew6180** [comment]
this was fixed awhile ago, forgot to close.
