### ISSUE TITLE
[Cooldown Monitor] Panel problem.

### ISSUE THREAD

**Issue by mrnuggets** [ajseward/RaidAssist_WotLK#12]
So i've also noticed that all panels work as one atm. A little hard for me to explain, but ill show you a video. The only thing you can do right now is separate the externals and raid CDs.

Basically i can't have a window with just Divine Sac or Aura Mastery.

The same goes for the external cooldowns. I can't have a window with just Hand of Sacrifice for example.

https://www.youtube.com/watch?v=xVEW7BoKbOk

**Comment by andrew6180** [comment]
This is how it works on the retail version. 

I may add this later but probably not.
