### ISSUE TITLE
Cooldowns don't account for glyphs or talent reductions.

### ISSUE THREAD

**Issue by andrew6180** [ajseward/RaidAssist_WotLK#13]

**Comment by Zidras** [comment]
I'm not sure this is fixed. Lay on Hands on that case was untalented.
![image](https://user-images.githubusercontent.com/10605951/88460131-df4a7500-ce91-11ea-8b59-b74287699dd9.png)

**Comment by coolaken** [comment]
> I'm not sure this is fixed. Lay on Hands on that case was untalented.
> ![image](https://user-images.githubusercontent.com/10605951/88460131-df4a7500-ce91-11ea-8b59-b74287699dd9.png)

can you share me the WA string?THX
