### ISSUE TITLE
Raid Cooldowns 

### ISSUE THREAD

**Issue by Nahoda** [ajseward/RaidAssist_WotLK#17]
Hello, Raid CDs would be great if they could be separated to more panels. Now if you make two panels both will show same CDs..  Would be good if you could separate one panel for paladin CDs, one for druid.. etc.. 

You can now configure more panels but they share the checkboxes.. 

Also icon size could match bar height.. And sometimes length of the bar extends and some bars are longer than others..

**Comment by andrew6180** [comment]
Looking into this.
