### ISSUE TITLE
[Bug] Chat spam after changing the raidleader

### ISSUE THREAD

**Issue by MaelKoT** [ajseward/RaidAssist_WotLK#19]
I was the raid leader in charge of the loot.

I transferred the rights to loot to another person, transferred the rights of the leader of the raid to him - and the addon began to unstoppably spam into the chat.

There are only 5 messages in the image, but in fact there are 1 message every second ...

![image](https://user-images.githubusercontent.com/2527033/89782727-80862c00-db1e-11ea-8f17-e14cc40c4843.png)

**Comment by andrew6180** [comment]
Until this is fixed you can reload ui to stop it
