### ISSUE TITLE
[Cooldown Monitor] Aura Mastery shows the wrong CD.

### ISSUE THREAD

**Issue by mrnuggets** [ajseward/RaidAssist_WotLK#4]
Aura Mastery shows the wrong CD. It shows 3 minutes instead of two.

https://youtu.be/eQYufiypJ_Q

-- There seems to be an overall problem with the cooldown monitor, spells not showing, such as Hand of Sacrifice. Won't add any further issues to this, since i don't have all the spells.

**Comment by andrew6180** [comment]
don't worry too much about spamming. Most of this is still pretty janky. 

If you're using details you will probably need to wait for https://github.com/Bunny67/Details-WotLK/pull/28 to be accepted for the missing CDs to properly show up 

(raid assist and details use the same framework)
