### ISSUE TITLE
[Cooldown Monitor] Lay on Hands

### ISSUE THREAD

**Issue by mrnuggets** [ajseward/RaidAssist_WotLK#5]
Lay on Hands isn't working.

**Comment by mrnuggets** [comment]
Also noticed that it's the wrong SpellID for Lay on Hands but correcting it didn't help.

48788 correct spellID for LoH.

**Comment by mrnuggets** [comment]
Ehm, i'm not sure if there's a work around for this, but there are talents, and glyphs that reduce the cooldown of Lay on Hands, and i've also noticed that the CD is set to 10 minutes, when the lowest is 11 minutes.

**Comment by andrew6180** [comment]
moving all these issues to a single issue 
https://github.com/ajseward/RaidAssist_WotLK/issues/13
