### ISSUE TITLE
[Cooldown Monitor] Tranquility

### ISSUE THREAD

**Issue by mrnuggets** [ajseward/RaidAssist_WotLK#7]
Tranquility doesn't work.

**Comment by andrew6180** [comment]
https://imgur.com/Um8NtMl 

I have no issue with it. 

![image](https://user-images.githubusercontent.com/16847730/86171335-685bcf80-bad1-11ea-962f-33d15edc3046.png)
here are my settings, but it shouldn't matter.

**Comment by mrnuggets** [comment]
When used it doesn't go on CD.

https://youtu.be/fl0Und2ADbc

**Comment by andrew6180** [comment]
is he using max rank? I don't see any reason it wouldn't be tracking.

**Comment by mrnuggets** [comment]
Ah yep sorry about that, works fine now, forgot to learn highest ranking skill for tranq.

Now the problem is it's the wrong CD. It's 3 min instead of 8.

**Comment by andrew6180** [comment]
A lot of abilities have variable cooldowns. At the moment it's assuming the player has the reduced cooldown talented.

**Comment by andrew6180** [comment]
https://github.com/ajseward/RaidAssist_WotLK/issues/13
